In [9]:
import pandas as pd

df = pd.read_excel("excel/Stock.xlsx",index_col="Name")
df

                             Category    Price  Amount
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900.0    10.0
ปากกา                 อุปกรณ์การเรียน    200.0     5.0
โคมไฟ                เครื่องใช้ในบ้าน   1200.0     7.0
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750.0     1.0
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500.0     0.0
เสื้อยืดคอกลม                เสื้อผ้า    500.0     2.0
กางเกงยีนต์                  เสื้อผ้า    999.0     8.0
ตุ๊กตาหมีพูห์                 ของเล่น    950.0     5.0
โซฟา                     เฟอร์นิเจอร์   5000.0     5.0
จาน                       เครื่องครัว    250.0     4.0
ทีวี                  เครื่องใช้ไฟฟ้า  15000.0     7.0
ยางลบ                 อุปกรณ์การเรียน     20.0     5.0
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500.0     7.0
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850.0     5.0
รถบังคับ                      ของเล่น    500.0     6.0

In [10]:
cols = ["Name","Price","Category"]
products = [['หูฟัง',1500,"อุปกรณ์คอมพิวเตอร์"],["สายชาร์จ",500,"อุปกรณ์คอมพิวเตอร์"]]

In [11]:
newdf = pd.DataFrame(data=products,columns=cols)
newdf.set_index('Name',inplace=True)
newdf

          Price            Category
Name
หูฟัง      1500  อุปกรณ์คอมพิวเตอร์
สายชาร์จ    500  อุปกรณ์คอมพิวเตอร์

In [12]:
df = df.append(newdf)
df

                             Category    Price  Amount
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900.0    10.0
ปากกา                 อุปกรณ์การเรียน    200.0     5.0
โคมไฟ                เครื่องใช้ในบ้าน   1200.0     7.0
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750.0     1.0
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500.0     0.0
เสื้อยืดคอกลม                เสื้อผ้า    500.0     2.0
กางเกงยีนต์                  เสื้อผ้า    999.0     8.0
ตุ๊กตาหมีพูห์                 ของเล่น    950.0     5.0
โซฟา                     เฟอร์นิเจอร์   5000.0     5.0
จาน                       เครื่องครัว    250.0     4.0
ทีวี                  เครื่องใช้ไฟฟ้า  15000.0     7.0
ยางลบ                 อุปกรณ์การเรียน     20.0     5.0
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500.0     7.0
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850.0     5.0
รถบังคับ                      ของเล่น    500.0     6.0
หูฟัง              อุปกรณ์คอมพิวเตอร์   1500.0     NaN
สายชาร์จ           อุปกรณ์คอมพิวเตอร์    500.0     NaN