In [27]:
import pandas as pd 

df = pd.read_excel("excel/dataupdate.xlsx","weather",index_col="Day")

In [28]:
df[df.Temperature<=20]

            Temperature  WindSpeed    Event
Day
2020-12-04           19          3  แดดร้อน
2020-12-05           20          5   เมฆมาก
2020-12-09           17          5   เมฆมาก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก

In [29]:
df[df.Event == "แดดร้อน"]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-04           19          3  แดดร้อน
2020-12-10           24          6  แดดร้อน
2020-12-12           27          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-15           28          4  แดดร้อน
2020-12-16           27          7  แดดร้อน
2020-12-19           25          7  แดดร้อน
2020-12-25           34          5  แดดร้อน

In [32]:
df.loc[(df.Event=="ฝนตก") & (df.Temperature>=35)]

            Temperature  WindSpeed Event
Day
2020-12-07           36          4  ฝนตก
2020-12-30           35          2  ฝนตก

In [35]:
df.loc[(df.Temperature.isin([18,20,25]))]

            Temperature  WindSpeed    Event
Day
2020-12-05           20          5   เมฆมาก
2020-12-06           25          6     ฝนตก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก
2020-12-19           25          7  แดดร้อน
2020-12-21           25          5   เมฆมาก
2020-12-26           25          8     ฝนตก

In [37]:
df.loc[(df.Temperature.isin([18,20,25])) & (df.Event.isin(["ฝนตก"]))]

            Temperature  WindSpeed Event
Day
2020-12-06           25          6  ฝนตก
2020-12-17           20          8  ฝนตก
2020-12-18           18          5  ฝนตก
2020-12-26           25          8  ฝนตก

In [38]:
df.loc[(df.Temperature.isin([18,20,25]))][df.Event=="ฝนตก"]

C:\Users\Keng\AppData\Local\Temp/ipykernel_11352/3370229534.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.loc[(df.Temperature.isin([18,20,25]))][df.Event=="ฝนตก"]

            Temperature  WindSpeed Event
Day
2020-12-06           25          6  ฝนตก
2020-12-17           20          8  ฝนตก
2020-12-18           18          5  ฝนตก
2020-12-26           25          8  ฝนตก